server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://121.36.19.76:3306/mall?serverTimezone=GMT
    username: root
    password: asdf;lkj
    hikari:
      max-lifetime: 61000
  redis:
    host: 121.36.19.76
    password: asdf;lkj
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: true
      logic-not-delete-value: false
mall:
  upload:
    directory: /home/yikang/language/upload/
  category:
    level: 3
