server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://121.36.19.76:3306/mall?serverTimezone=GMT
    username: root
    password: asdf;lkj
    hikari:
      max-lifetime: 61000
  redis:
    host: 121.36.19.76
    port: 6379
    password: asdf;lkj
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mall:
  upload:
    directory: F:\\upload\\
