server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://yikang.pub:3306/mall?useUnicode=true&serverTimezone=GMT&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: asdf;lkj
  redis:
    host: yikang.pub
    port: 6379
    password: asdf;lkj
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mall:
  upload:
    directory: F:\\upload\\
