server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_mall?useUnicode=true&serverTimezone=GMT&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: root
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mall:
  upload:
    directory: F:\\upload\\
